name: Provider Design Feedback

# Create/Edit OpenAPI Document in SwaggerHub
# Sync OpenAPI -> SCM with Github Sync - https://support.smartbear.com/swaggerhub/docs/integrations/github-sync.html
# Version number = <OAS Version>-<GitHub Commit SHA>-design
# OpenAPI + Provider Test Report = Provider Contract Uploaded to Pactflow
# *** Test Report is just OAS file, as the design will not be tested against an API mock or real implementation at this stage ***
# Pactflow compares OpenAPI against any registered consumers
# Visiblity into affected consumers visible via can-i-deploy

on:
  push:
    branches: ['swaggerhub*', 'main']
    paths:
      - 'oas/**'
  pull_request:
    branches: ['main']
    paths:
      - 'oas/**'

  workflow_dispatch:

env:
  oas_file_location: oas/swagger.yaml
  application_name: pactflow-example-provider
  PACT_BROKER_BASE_URL: https://saflow.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

jobs:
  pact-publish-oas-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get version of OAS
        run: |
          sudo snap install yq 
          UNIQUE_VERSION=$(yq '.info.version' ${{ env.oas_file_location }})-${{ github.sha }}-design
          echo "version=${UNIQUE_VERSION}" >> $GITHUB_ENV
      - name: publishing ${{ env.application_name }} with ${{ env.version }} to Pactflow
        uses: pactflow/actions/publish-provider-contract@v1.0.1
        env:
          oas_file: ${{ env.oas_file_location }}
          results_file: ${{ env.oas_file_location }}
    outputs:
      version: ${{ env.version }}

  pact-can-i-deploy:
    strategy:
      matrix:
        environment: [test, production]
      fail-fast: false
    needs: pact-publish-oas-action
    runs-on: ubuntu-latest
    steps:
      - name: can-i-deploy ${{ env.application_name }} to ${{ matrix.environment }}
        uses: pactflow/actions/can-i-deploy@v1.0.1
        env:
          to_environment: ${{ matrix.environment }}
          version: ${{ needs.pact-publish-oas-action.outputs.version }}
